version: '3'
services:
  web:
    container_name: ward_vue_dev_test
    build: .
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - '/app/node_modules'
      - '.:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
